- name: Setting up app config
  template: src=supervisor-app-conf.j2 dest=/etc/supervisor/conf.d/{{ app_name }}.conf owner=root group=root mode=0644

- name: reread supervisorctl
  shell: supervisorctl reread
  register: reread

- name: reload supervisorctl
  shell: supervisorctl reload
  register: reload

- name: check app status
  shell: supervisorctl status
  register: status
